name: Update Stock Data Daily

on:
  schedule:
    - cron: '0 18 * * *'  # 每天 UTC 時間 18:00 (台灣時間凌晨2點)
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3  # 這裡使用 v3 並設置 persist-credentials
      with:
        persist-credentials: true  # 這行確保有推送權限
        fetch-depth: 0  # 獲取所有歷史記錄

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance prophet plotly pandas
    
    - name: Generate static files
      run: python generate_static.py
    
    - name: Commit and push changes
      run: |

        rm -rf docs
    
        mkdir -p docs
        cp -r output/* docs/
    
        touch docs/.nojekyll
    
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Move output to docs for GitHub Pages"
        git push
