- name: Commit and push changes
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 預設的 token，但可能無法 push
    # 或改用 Personal Access Token (PAT)
    # GITHUB_TOKEN: ${{ secrets.PAT }}  # 需先在 Repo Settings > Secrets 設定
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add index.html data.json *.html 
    git commit -m "Update stock data"
    git push origin main  # 明確指定分支
