name: Update Stock Data Daily

on:
  schedule:
    - cron: '0 10 * * *'  # UTC 10:00 = 台灣時間 18:00
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ticker: ['2330.TW', '2409.TW', '2317.TW']  # 只生成允許的股票報告
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance prophet plotly pandas jinja2
    
    - name: Generate static files
      run: python generate_static.py
    
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 或用 PAT
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html data.json *.html 
        git commit -m "Update stock data" || echo "No changes to commit"
        git push origin main || echo "Push failed"
